import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F4F4',
  },
  tittle: {
    fontWeight: 'bold',
    fontSize: 20,
    margin: 10,
  },
  logo: {
    height: 45,
    width: 190,
    marginTop: '25%',
    alignSelf: 'center',
  },
  textcreate: {
    fontSize: 18,
    color: '#5B5B5B',
    marginTop: 25,
    alignSelf: 'center',
    fontWeight: '400',
    fontFamily: 'Nunito',
    marginBottom: 16,
  },
  forgotpassword: {
    alignSelf: 'center',
    fontSize: 14,
    color: '#2E3283',
    marginTop: 17,
  },
  loginwithtext: {
    alignSelf: 'center',
    fontSize: 14,
    color: '#2E3283',
    marginTop: -10,
    marginHorizontal: 20,
  },
  loginwithline: {
    height: 1,
    backgroundColor: '#959595',
    width: 100,
  },

  loginwith: {
    flexDirection: 'row',
    marginTop: 20,
    alignContent: 'center',
    justifyContent: 'center',
    marginBottom: 40,
  },
  textinput: {
    height: 50,
    width: 300,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    borderRadius: 5,
    color: '#959595',
    marginTop: 25,
  },
  eyespassword: {
    alignSelf: 'center',
    right: 12,
    position: 'absolute',
    height: 15,
    widt: 15,
  },
  socialmediaicon: {
    width: 50,
    height: 50,
    marginHorizontal: 25,
  },
  margin: {
    marginTop: 16,
  },
  buttoncreate: {
    height: 50,
    width: 300,
    backgroundColor: '#2E3283',
    borderRadius: 5,
    alignSelf: 'center',
    marginTop: 25,
    justifyContent: 'center',
  },
  textbutton: {
    fontSize: 14,
    color: 'white',
    textAlign: 'center',
  },
  footer: {
    backgroundColor: '#FFFFFF',
    height: 40,
    width: '100%',
    position: 'absolute',
    bottom: 0,
    shadowRadius: 50,
    borderColor: 'black',
    borderRadius: 3,
    shadowOffset: 40,
    shadowOpacity: 0.7,
    elevation: 55,
    shadowColor: 'black',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
  },
  footertext: {
    fontSize: 14,
    alignSelf: 'center',
    color: '#5B5B5B',
  },
  iconhomepage: {
    width: 72,
    height: 72,
    marginHorizontal: 8,
  },
  banner: {
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 10,
    width: 339,
    height: 137,
    shadowColor: '#7373746E',
    alignSelf: 'center',
    marginTop: -85,
    borderColor: 'white',
    shadowRadius: 22,
    elevation: 55,
    shadowOffset: {
      height: 1,
      width: 1,
    },
  },
  martinpoint: {
    height: '100%',
    width: '100%',
    backgroundColor: '#F4F4F4',
    borderRadius: 25,
    marginTop: -26,
  },

  container1: {
    backgroundColor: 'white',
    borderRadius: 8,
    paddingBottom: 40,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.29,
    shadowRadius: 4.65,
    elevation: 7,
  },
  image: {
    height: 300,
  },
  header: {
    color: '#222',
    fontSize: 28,
    fontWeight: 'bold',
    paddingLeft: 20,
    paddingTop: 20,
  },
  body: {
    color: '#222',
    fontSize: 18,
    paddingLeft: 20,
    paddingLeft: 20,
    paddingRight: 20,
  },
});

export default styles;
